device: cuda
dev: False
deterministic: False

ct_data: ./data/smat_ct_bg=012.yml
mr_data: ./data/smat_mr_bg=03.yml


updater:
    class_path: modules.dann.cyclegan.PartUpdaterCycleGanDANN

trainer:
    class_path: modules.dann.part_trainer.PartTrainerDANN
    init_args:
        max_iter: 1200
        eval_step: 100
        checkpoint_dir: ./checkpoints/
        metric: null # specified in validator
        dev: ${dev}
        validator:
            class_path: modules.validator.categorical.CategoricalMinValidator
            init_args:
                metric:
                    class_path: monai.metrics.DiceMetric
                    init_args:
                        include_background: True
                        reduction: mean
                        get_not_nans: False
                is_train: True
                device: ${device}
                num_classes: 4
        

module:
    class_path: modules.dann.cyclegan.CycleGanDANNModule
    init_args:
        optimizer: AdamW
        lr: 0.001
        roi_size: [512, 512]
        sw_batch_size: 1
        pretrained: null
        device: ${device}
        cycle_gan_ckpt_dir: C:/Users/User/Desktop/Kevin/pytorch-CycleGAN-and-pix2pix/checkpoints/ct_pdff_ssim2/
        ct_criterion: 
            class_path: lib.loss.target_adaptative_loss.TargetAdaptativeLoss
            init_args:
                num_classes: 4
                background_classes: [0, 1, 2]
        mr_criterion: 
            class_path: lib.loss.target_adaptative_loss.TargetAdaptativeLoss
            init_args:
                num_classes: 4
                background_classes: [0, 3]
        feat_extractor:
            class_path: networks.unet.BasicUNetNoSkipEncoder
            init_args:
                spatial_dims: 2
                in_channels: 1
        predictor:
            class_path: networks.unet.BasicUNetNoSkipDecoder
            init_args:
                spatial_dims: 2
                out_channels: 4


